version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: postgre_sql
    volumes:
      - data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    networks:
      work:
        ipv4_address: 172.18.0.4
  adminer:
    image: adminer
    container_name: postgre_adminer
    restart: always
    ports:
      - 5433:5433
    networks:
      work:
        ipv4_address: 172.18.0.5
networks:
  work:
    external: true
volumes:
  data: {}
