TITLE 挂载vhd
DISKPART /S DISKPART.TXT

@REM DISKPART.TXT：（DISKPART命令脚本）
SELECT VDISK FILE="D:\CODE.VHDX"
ATTACH VDISK
LIST DISK
LIST VDISK
LIST PARTITION
SELECT PARTITION=1
ASSIGN LETTER=P
LIST VOLUME

@REM 取消挂载
DETACH VDISK
