SET FOLDER_PATH=B:\y
SET CURRENT_USER=yashi
SET LOG=B:\ICACLS-B.LOG
IF NOT EXIST "%FOLDER_PATH%" MKDIR "%FOLDER_PATH%" >>%LOG%
ICACLS "%FOLDER_PATH%" /inheritance:r >>%LOG%
ICACLS "%FOLDER_PATH%" /grant:r "%CURRENT_USER%":F >>%LOG%
ICACLS "%FOLDER_PATH%" /deny "Everyone":(F) >>%LOG%
EXIT