@ECHO OFF
SETLOCAL ENABLEDELAYEDEXPANSION
SET BASE_X=%1
SET BASE_Y=%2
SET OFF_X=%3
SET OFF_Y=%4
IF "%~4"=="" (
	ECHO USE: %~nx0 [X] [Y] [+-X] [+-Y]
    EXIT /B
)
CALL :GET_RANDOM %BASE_X% %OFF_X% FINAL_X
CALL :GET_RANDOM %BASE_Y% %OFF_Y% FINAL_Y
ECHO adb %ADBS% shell input tap %FINAL_X% %FINAL_Y%
adb %ADBS% shell input tap %FINAL_X% %FINAL_Y%
GOTO :EOF

:GET_RANDOM
SET /A _BASE=%1
SET /A _OFFSET=%2
SET /A _SPAN=(_OFFSET * 2) + 1
SET /A _MIN=_BASE - _OFFSET
SET /A %3=%RANDOM% %% _SPAN + _MIN
GOTO :EOF
