vi /etc/resolv.conf

# Generated by NetworkManager
# nameserver 8.8.8.8
# nameserver 1.1.1.1

# options timeout:2 attempts:3 rotate single-request-reopen
# ; generated by /usr/sbin/dhclient-script
# nameserver 100.100.2.136
# nameserver 100.100.2.138