TITLE ollama导出模型

@REM 这里以qwen:7b为例，先查看模型信息
ollama show --modelfile qwen:7b
@REM FROM 就是路径

COPY "%OLLAMA_MODELS%\blobs\sha256-46bb65206e0e2b00424f33985a5281bd21070617ebcfda9be86eb17e6e00f793" "D:\qwen_7b.gguf"

TITLE ollama导入模型(.gguf 格式，搜索时可以加 -GGUF)

@REM 需要准备 Modelfile 文件
@REM FROM /path/to/qwen_7b.gguf
@REM 可以根据上面的 ollama show --modelfile 输出取出完整 Modelfile:
@REM # Modelfile generated by
@REM ......
@REM PARAMETER stop "\"<|im_end|>\""

@REM 开始导入
ollama create qwen:7b -f Modelfile
@REM transferring model data 复制一个完整的模型
@REM creating model layer  生成一个新的模型文件，和原来模型大小一样， 结束后会删除掉？生成一个很小的layer文件

@REM https://blog.csdn.net/weixin_37841024/article/details/138183851
