DROP USER 'yashiuser'@'%';

CREATE USER 'yashiuser'@'%' IDENTIFIED BY 'YUjDM78KiyTHnFT4iGe1JPR8IcAqFZ99De4JvAC7c7mLAFJIEVEfJioJOV47VCte3EIYVIWm3MCWGogf';

GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,ALTER,INDEX,DROP ON yashiwc.* TO 'yashiuser'@'%';
